version: "3.9"
services:
  clientapiscraper:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: clientapiscraper
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
